const actions = {
    UPDATE_PAGE: 'UPDATE_PAGE',
    CREATE_POST: 'CREATE_POST',
    UPDATE_POST: 'UPDATE_POST',
    EDIT_POST: 'EDIT_POST',
    DELETE_POST: 'DELETE_POST',
    SELECT_POST: 'SELECT_POST',
    TOGGLE_CREATE_POP_UP: 'TOGGLE_CREATE_POP_UP',
    TOGGLE_VIEW_POP_UP: 'TOGGLE_VIEW_POP_UP', 
    TOGGLE_EDIT_POP_UP: 'TOGGLE_EDIT_POP_UP',
    DELETE_SELECTED: 'DELETE_SELECTED',
    HIDE_SELECTED: 'HIDE_SELECTED',
    CONTENT_CHANGE: 'CONTENT_CHANGE',
    SUBJECT_CHANGE: 'SUBJECT_CHANGE',
    TOGGLE_SHOW_MODE: 'TOGGLE_SHOW_MODE',
    GET_POSTS: 'GET_POSTS',
    TOGGLE_MOBILE_MENU: 'TOGGLE_MOBILE_MENU',
}

export {
    actions
}